define

movie-recommendation-by-genre-rule sub rule
when {
    (film:$watchedMovie, movie-genre:$genre) isa belongs-to-genre;
    (film:$movie, movie-genre:$genre) isa belongs-to-genre;
    (user: $user, watched-movie:$watchedMovie) isa watch;
    $watchedMovie != $movie;
}
then {
    (user: $user, recommended-movie: $movie) isa movie-recommendation;
};

movie-recommendation-by-fav-actor-rule sub rule
when {
    (favorite-actor: $act, user:$user) isa is-favorite-actor;
    (cast:$act, film:$movie) isa is-cast-of-movie;
    (user:$user, watched-movie:$watchedMovie) isa watch;
    $watchedMovie != $movie;
}
then {
    (user:$user, recommended-movie:$movie) isa movie-recommendation-by-fav-actor;
};